apiVersion: v1
kind: Service
metadata:
  name: placeholder
  labels:
    app: placeholder
spec:
  type: ClusterIP
  selector:
    app: placeholder
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
