apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: placeholder-svc
  name: placeholder-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: placeholder-svc
  strategy: {}
  template:
    metadata:
      labels:
        app: placeholder-svc
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "placeholder-svc"
        dapr.io/app-port: "3000"
        dapr.io/enable-api-logging: "true"
        dapr.io/log-level: "debug"
    spec:
      containers:
        - image: placeholder-svc
          name: placeholder-svc
          imagePullPolicy: IfNotPresent
          resources: {}
          envFrom:
            - secretRef:
                name: placeholder-svc
status: {}
