apiVersion: v1
kind: Service
metadata:
  name: placeholder-svc
  labels:
    app: placeholder-svc
spec:
  type: ClusterIP
  selector:
    app: placeholder-svc
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
