apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: placeholder
  name: placeholder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: placeholder
  strategy: {}
  template:
    metadata:
      labels:
        app: placeholder
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "placeholder"
        dapr.io/app-port: "3000"
        dapr.io/enable-api-logging: "true"
        dapr.io/log-level: "debug"
    spec:
      containers:
        - image: placeholder
          name: placeholder
          imagePullPolicy: IfNotPresent
          resources: {}
          envFrom:
            - secretRef:
                name: placeholder
status: {}
